src/explainable/urls.py
from django.conf.urls import url

from . import views

app_name = 'explainable'
urlpatterns = [
    # /explainable/
    url(r'^$', views.index, name='index'),
    # /explainable/example
    url(r'^example/$', views.example, name='example'),
    # /explainable/flip/<stage>
    url(r'^flip/(?P<stage>[0-9]+)/$', views.flip, name = 'flip')
]

# all pointing to same view (make sure to have optional default parameter for definition in view)
# urlpatterns = patterns('',
#     url(r'^project_config/$', views.foo),
#     url(r'^project_config/(?P<product>\w+)/$', views.foo),
#     ulr(r'^project_config/(?P<product>\w+)/(?P<project_id>\w+)/$', views.foo),
# )

src/website/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^explainable/', include('explainable.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/explainable/backend/models/x_linearsgdc.py
from sklearn.linear_model import SGDClassifier
from ..explain.explain import Explainer, ExplainableModel
from ..optimize.optimize import LPOptimizer
from ..preprocess.process import Preprocesser

class ExplainableSGDClassifier(ExplainableModel):

    def __init__(self):
        self.reg = SGDClassifier()
        self.explainer = Explainer(LPOptimizer())
        self.pp = Preprocesser()

    def fit(self, X, y):
        """
        Trains the model with the provided training data.
        """
        encX = self.pp.fit_transform(X)
        self.reg.fit(encX, y)
        self.data = encX

    def predict(self, X):
        """
        Predicts the output given the trained model and an observation.
        """
        encX = self.pp.transform(X)
        return self.reg.predict(encX)

    def score(self, X, y):
        """
        Returns the coefficient of determination of the model.
        """
        return self.reg.score(self.pp.transform(X), y)

    def explain(self, X):
        """
        Returns an explanation given the trained model and an observation.
        """
        return self.explainer.explain(self.reg, self.data, self.pp.transform(X))

src/explainable/backend/models/x_linearsvc.py
from sklearn.svm import LinearSVC
import numpy as np
from ..explain.explain import Explainer, ExplainableModel
from ..optimize.optimize import LPOptimizer
from ..preprocess.process import Preprocesser

class ExplainableLinearSVC(ExplainableModel):

    def __init__(self):
        self.reg = LinearSVC()
        self.explainer = Explainer(LPOptimizer())
        self.pp = Preprocesser()

    def fit(self, X, y):
        """
        Trains the model with the provided training data.
        """
        encX = self.pp.fit_transform(X)
        self.reg.fit(encX, y)
        self.data = encX

    def predict(self, X):
        """
        Predicts the output given the trained model and an observation.
        """
        encX = self.pp.transform(X)
        return self.reg.predict(encX)

    def score(self, X, y):
        """
        Returns the coefficient of determination of the model.
        """
        return self.reg.score(self.pp.transform(X), y)

    def coefs(self):
        return np.concatenate((self.reg.intercept_, self.reg.coef_[0]), axis = 0)

    def explain(self, X):
        """
        Returns an explanation given the trained model and an observation.
        """
        return self.explainer.explain(self.reg, self.data, self.pp.transform(X))

src/explainable/backend/models/x_perceptron.py
from sklearn.linear_model import Perceptron
from ..explain.explain import Explainer, ExplainableModel
from ..optimize.optimize import LPOptimizer
from ..preprocess.process import Preprocesser

class ExplainablePerceptron(ExplainableModel):

    def __init__(self):
        self.reg = Perceptron()
        self.explainer = Explainer(LPOptimizer())
        self.pp = Preprocesser()

    def fit(self, X, y):
        """
        Trains the model with the provided training data.
        """
        encX = self.pp.fit_transform(X)
        self.reg.fit(encX, y)
        self.data = encX

    def predict(self, X):
        """
        Predicts the output given the trained model and an observation.
        """
        encX = self.pp.transform(X)
        return self.reg.predict(encX)

    def score(self, X, y):
        """
        Returns the coefficient of determination of the model.
        """
        return self.reg.score(self.pp.transform(X), y)

    def explain(self, X):
        """
        Returns an explanation given the trained model and an observation.
        """
        return self.explainer.explain(self.reg, self.data, self.pp.transform(X))

src/explainable/backend/models/x_svc.py
from sklearn.svm import SVC
from explain.explain import Explainer, ExplainableModel
from optimize.optimize import PatternSearchOptimizer

class ExplainableSVC(ExplainableModel):
    
    def __init__(self):
        self.reg = SVC(kernel = 'linear')
        self.explainer = Explainer(PatternSearchOptimizer())
    
    def fit(self, X, y):
        """
        Trains the model with the provided training data.
        """
        self.reg.fit(X, y)
        self.data = X
    
    def predict(self, X):
        """
        Predicts the output given the trained model and an observation.
        """
        return self.reg.predict(X)
    
    def score(self, X, y):
        """
        Returns the coefficient of determination of the model.
        """
        return self.reg.score(X, y)
    
    def explain(self, X):
        """
        Returns an explanation given the trained model and an observation.
        """
        return self.explainer.explain(self.reg, self.data, X)

src/explainable/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os

# Create your models here.
class Module(models.Model):
    module_title = models.CharField(max_length=200)
    module_route = models.CharField(max_length=200)
    module_description = models.CharField(max_length=200)
    module_color = models.CharField(max_length=200)

    def __str__(self):
        return self.module_title + ": " + self.module_description

class Dataset(models.Model):
    dataset_url = models.CharField(max_length=200)

    def __str__(self):
        return self.dataset_url

class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name

class ExplainableModel(models.Model):
    model_name = models.CharField(max_length=200)
    model_color = models.CharField(max_length=200)

    def __str__(self):
        return self.model_name

src/explainable/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader, RequestContext
from django.conf import settings
import random
import numpy as np
import plotly
import csv
import plotly.graph_objs as go
from .models import Module, Dataset, OverwriteStorage, ExplainableModel
from .backend.models.x_linearsvc import ExplainableLinearSVC
from .backend.models.x_linearsgdc import ExplainableSGDClassifier
from .backend.models.x_perceptron import ExplainablePerceptron
from .backend.utils.datasets import Datasets
from .backend.view import plotmaker
import ast

def index(request):
    explainable_modules = Module.objects.all()
    context = {
        'modules' : explainable_modules
    }
    return render(request, 'explainable/index.html', context)

def example(request):
    obs = [[5.1, 2.8, 3, 0.4]]
    X, Y, plotData, chartLayout = plotmaker.makeIris(obs)

    model = ExplainableLinearSVC()
    model.fit(X, Y)
    explanation = model.explain(obs)

    hyperplaneData = plotmaker.hyperplane(model.coefs(), [0, 1, 2])
    flippedData = plotmaker.flip(explanation, obs)

    chartData = plotData + hyperplaneData + flippedData

    myChart = plotly.offline.plot({"data": chartData,
                                   "layout": chartLayout},
                                   output_type = "div",
                                   show_link = "False",
                                   include_plotlyjs = "False",
                                   link_text="")
    return render(request, 'explainable/example.html', {'features' : explanation.features(), 'confidence' : explanation.confidence(), 'chart' : myChart})

def flip(request, stage=1):
    module = get_object_or_404(Module, module_route='flip')
    stage = int(stage)
    if stage == 1:
        return render(request, 'explainable/flip.html', {"module" : module, "stage" : 1})
    elif stage == 2:
        data = request.FILES['data']
        fs = OverwriteStorage()
        filename = fs.save(data.name, data)
        uploaded_file_url = fs.url(filename)
        if len(Dataset.objects.filter(dataset_url = uploaded_file_url)) == 0:    # if non-existent, then save to database
            dataObject = Dataset(dataset_url = uploaded_file_url)
            dataObject.save()
        return render(request, 'explainable/flip.html', {"module": module, "stage" : 2, "uploaded_file_url" : uploaded_file_url, "models": ExplainableModel.objects.all()})
    elif stage == 3:
        selected_model = request.POST.get('selected_model', 'Linear Support Vector Classifier')
        uploaded_file_url = request.POST.get('uploaded_file_url', 'ERROR')
        header = []
        with open(settings.BASE_DIR + uploaded_file_url, 'rt') as f:
            reader = csv.reader(f, delimiter = ',', )
            header = next(reader)
        return render(request, 'explainable/flip.html', {"module" : module, "stage" : 3, "uploaded_file_url" : uploaded_file_url, "selected_model" : selected_model, "features" : range(1, len(header)), "num_features" : len(header)})
    elif stage == 4:
        selected_model = request.POST.get('selected_model', 'Linear Support Vector Classifier')
        uploaded_file_url = request.POST.get('uploaded_file_url', 'ERROR')
        num_features = int(request.POST.get('num_features', []))
        int_idxs = []
        str_idxs = []
        for i in range(1, num_features):
            res = request.POST.get(str(i), -1)
            if res == -1:
                str_idxs.append(i - 1)
            else:
                int_idxs.append(i - 1)
        return render(request, 'explainable/flip.html', {"module" : module, "stage" : 4, "uploaded_file_url" : uploaded_file_url, "selected_model" : selected_model, "int_idxs" : int_idxs, "str_idxs" : str_idxs})
    elif stage == 5:
        selected_model = request.POST.get('selected_model', 'Linear Support Vector Classifier')
        uploaded_file_url = request.POST.get('uploaded_file_url', 'ERROR')
        int_idxs = ast.literal_eval(request.POST.get('int_idxs', '[]'))
        str_idxs = ast.literal_eval(request.POST.get('str_idxs', '[]'))
        observation = request.POST.get('observation', "")
        obs = [ast.literal_eval('[' + observation + ']')]
        model = None
        if selected_model == 'Linear Support Vector Classifier':
            model = ExplainableLinearSVC()
        elif selected_model == 'Linear Stochastic Gradient Descent Classifier':
            model = ExplainableSGDClassifier()
        elif selected_model == 'Perceptron':
            model = ExplainablePerceptron()
        else:
            model = ExplainableLinearSVC() # default case, in case of some error

        X = []
        y = []
        with open(settings.BASE_DIR + uploaded_file_url, 'rt') as f:
            reader = csv.reader(f, delimiter = ',', )
            for ln in reader:
                features = []
                for i in range(len(ln)):
                    if i == (len(ln) - 1):
                        y.append(ln[i])
                    elif i in int_idxs:
                        features.append(float(ln[i]))
                    else:
                        features.append(str(ln[i]))
                X.append(features)

        y_vals = list(set(y))

        X, y = Datasets.binarize(X, y, y_vals[0], y_vals[1])

        model.fit(X, y)
        explanation = model.explain(obs)

        top_3_features = explanation.top_k(3)

        idxs = []
        for k, v in top_3_features:
            idxs.append(int(k[8:]))

        idxs = sorted(idxs, key=int)

        plotData, chartLayout = plotmaker.make(X, y, obs, idxs)

        hyperplaneData = plotmaker.hyperplane(model.coefs(), obs, idxs)
        flippedData = plotmaker.flip(explanation, obs, idxs)

        chartData = plotData + hyperplaneData + flippedData

        myChart = plotly.offline.plot({"data": chartData,
                                       "layout": chartLayout},
                                       output_type = "div",
                                       show_link = "False",
                                       include_plotlyjs = "False",
                                       link_text="")

        return render(request, 'explainable/flip.html', {"module" : module, "stage" : 5, "uploaded_file_url" : uploaded_file_url, "selected_model" : selected_model, "int_idxs" : int_idxs, "str_idxs" : str_idxs, "chart" : myChart, "confidence" : explanation.confidence()})
    else:
        return render(request, 'explainable/flip.html', {"module" : module, "stage" : -1})

src/explainable/templates/explainable/example.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'explainable/style.css' %}" />

<h1>Example</h1>
<p>This is a simple example using the <a href ="https://archive.ics.uci.edu/ml/datasets/Iris">Iris dataset</a> and a Linear Support Vector Classifier model.</p>
<p>{{ confidence }}</p>
<div style="width:1200;height:800">
{{ chart|safe }}
</div>

src/explainable/templates/explainable/flip.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'explainable/style.css' %}" />

<h5><a href="{% url 'explainable:index' %}">   < back    </a></h5>
<h1 style="text-decoration: underline {{ module.module_color }};">{{ module.module_title }}</h1>
<h4>{{ module.module_description }}</h4>

{% if stage == 1 %}
  <p><b>Step 1:</b> Upload a dataset. . .</p>
  <form action="{% url 'explainable:flip' stage=2 %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="data" />
    <input type="Submit" value="Upload" />
  </form>
  <p>. . .or choose from previously uploaded datasets:</p>

{% elif stage == 2 %}
  <p><span class="completed-step">Step 1:</span> File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  <p><b>Step 2:</b> Choose a model to train on your data:</p>
  <ul class="list-horizontal">
  {% for model in models %}
    <form method="post" action="{% url 'explainable:flip' stage=3 %}">
      {% csrf_token %}
      <input type="hidden" name="selected_model" value="{{ model.model_name }}" />
      <input type="hidden" name="uploaded_file_url" value = "{{ uploaded_file_url }}" />
      <li style="background-color: {{ model.model_color }}"><a href="#" onclick="document.forms[0].submit(); return false;">{{ model.model_name }}</a></li>
    </form>
  {% endfor %}
  </ul>

{% elif stage == 3 %}
  <p><span class="completed-step">Step 1:</span> File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  <p><span class="completed-step">Step 2:</span> Model chosen: <b>{{ selected_model }}</b></p>
  <p><b>Step 3:</b> Please indicate which features are integer-typed (assuming the remaining features are string-typed and that the last column is the label):</p>
  <form method="post" action = "{% url 'explainable:flip' stage=4 %}">
    {% csrf_token %}
    <ul class="list-horizontal">
      {% for index in features %}
        <li><input type="checkbox" name="{{ index }}" value="{{ index }}">{{ index }}</li>
      {% endfor %}
      <input type="hidden" name="selected_model" value="{{ selected_model }}" />
      <input type="hidden" name="uploaded_file_url" value = "{{ uploaded_file_url }}" />
      <input type="hidden" name="num_features" value = "{{ num_features }}" />
      <li><input type="submit" value="Done"></li>
    </ul>
  </form>

{% elif stage == 4 %}
  <p><span class="completed-step">Step 1:</span> File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  <p><span class="completed-step">Step 2:</span> Model chosen: <b>{{ selected_model }}</b></p>
  <p><span class="completed-step">Step 3:</span> Feature types specified.</p>
  <p><b>All Ready!</b> Enter an observation point to be explained (format as a list without brackets):</p>
  <form method="post" action = "{% url 'explainable:flip' stage=5 %}">
    {% csrf_token %}
    <input type="text" placeholder="100, 35.5, 'John'" name="observation">
    <input type="hidden" name="selected_model" value="{{ selected_model }}" />
    <input type="hidden" name="uploaded_file_url" value = "{{ uploaded_file_url }}" />
    <input type="hidden" name="int_idxs" value = "{{ int_idxs }}" />
    <input type="hidden" name="str_idxs" value = "{{ str_idxs }}" />
    <input type="submit" value="Submit">
  </form>

{% elif stage == 5 %}
  <p><span class="completed-step">Step 1:</span> File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  <p><span class="completed-step">Step 2:</span> Model chosen: <b>{{ selected_model }}</b></p>
  <p><span class="completed-step">Step 3:</span> Feature types specified.</p>
  <p><b>All Ready!</b> Enter an observation point to be explained (format as a list without brackets):</p>
  <form method="post" action = "{% url 'explainable:flip' stage=5 %}">
    {% csrf_token %}
    <input type="text" placeholder="100, 35.5, 'John'" name="observation">
    <input type="hidden" name="selected_model" value="{{ selected_model }}" />
    <input type="hidden" name="uploaded_file_url" value = "{{ uploaded_file_url }}" />
    <input type="hidden" name="int_idxs" value = "{{ int_idxs }}" />
    <input type="hidden" name="str_idxs" value = "{{ str_idxs }}" />
    <input type="submit" value="Submit">
  </form>
  <p><b>Confidence:</b> <span style="font-family: Courier">{{ confidence }}</span></p>
  <div style="width:1200;height:800">
  {{ chart|safe }}
  </div>

{% else %}
  <p>Something went wrong...</p>

{% endif %}

src/explainable/templates/explainable/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'explainable/style.css' %}" />

<h1>Explainable AI</h1>
<h2>Modules</h2>
{% if modules %}
    <ul class="list-horizontal">
    {% for module in modules %}
        {% with "explainable:"|add:module.module_route as route_url %}
        <li style="background-color: {{ module.module_color }}"><a href="{% url route_url stage=1 %}">{{ module.module_title }}</a></li>
        {% endwith %}
    {% endfor %}
    </ul>
{% else %}
    <p>No modules are currently available.</p>
{% endif %}